- newspack-custom-content-migrator.php
- src/Migrator/PublisherSpecific/GadisMigrator.php
Implements WP CLI command to import [Gadis](https://gadis.co.id) articles from SQL dump.
Import the SQL dump tables into your local WordPress database. Run the WP cli command:
```
$ wp newspack-content-migrator gadis-import-posts
```
| Table name                      | Import | Notes                                                                    |
| ------------------------------- | ------ | ------------------------------------------------------------------------ |
| `abouts`                        | -      |                                                                          |
| `academy_participant`           | -      |                                                                          |
| `academy_participant_details`   | -      | …
> Gadis articles migrator

- src/Migrator/PublisherSpecific/GadisMigrator.php
Implements the `newspack-content-migrator gadis-import-tv` command to import GadisTV content.
- Generates video or rich (generic) embed block
- Imports video thumbnail as the featured image (if available from oembed data)
> feat(Gadis): import GadisTV

- src/Migrator/PublisherSpecific/GadisMigrator.php
Use YouTube API to fetch videos published dates and skip non-YouTube videos.
Command:
```
wp newspack-content-migrator gadis-import-tv --youtube_api_key="{api-key}"
```
> feat(gadis): use youtube api to fetch videos date

- src/Migrator/PublisherSpecific/ElLiberoContentMigrator.php
- src/Migrator/PublisherSpecific/ElLiberoCustomCategoriesMigrator.php
Made several downgrades to El Libero code features to support PHP 7.4 which is what the Atomic platform runs on.
Please double-check if I've replace the arrow function code to closures correctly.
> Code compatibility PHP 7.4

- src/Migrator/PublisherSpecific/EnergeticCityMigrator.php
EnergeticCity provided us with an XML export of their posts. It contained posts between 2015 and 2019 which they would like on their site, since we weren't able to scrape them. I had to perform a certain portion of this migration locally. Another portion of the migration now requires to be executed on their live site. I've loaded the missing posts to missing_2_posts, which need to be brought over to wp_posts table.
> feat: needed two additional scripts to get EC's missing posts on their DB.

- src/Migrator/PublisherSpecific/BethesdaMagMigrator.php
A command that moves and do some cleaning of co-authors date from post meta to CAP.
> Feat(Bethesda): migrate co-authors data from meta to CAP

- newspack-custom-content-migrator.php
- src/Migrator/PublisherSpecific/CalMattersMigrator.php
Import missing featured images from a local folder `WP_CONTENT_DIR . "/missing_images`.
> feat(CalMatters): import missing featured images from local

- newspack-custom-content-migrator.php
- src/Migrator/PublisherSpecific/NewsroomCoNzMigrator.php
Reads postmeta saved by the Scraper Migrator Plugin, and turns it into the actual data that it should be.
> newsroom.co.nz custom migrator

- newspack-custom-content-migrator.php
- src/MigrationLogic/Posts.php
- src/Migrator/PublisherSpecific/IthacaVoiceMigrator.php
This is a migrator for Ithaca Voice galleries from the Best Wordpress Gallery plugin, I didn't make this as a general migrator for the plugin as the publisher have already the images hosted on their S3 bucket.
> feat(Ithaca Voice): Add gallery migrator

- src/Migrator/General/NextgenGalleryMigrator.php
The Next Generation Gallery plugin use a couple of shortcodes depending on the plugin version used, this PR handle this.
> feat(NGG): enable migrating multiple shortcodes

- newspack-custom-content-migrator.php
- src/Migrator/General/XMLMigrator.php
Created the initial version of General type XMLMigrator.
Shared just one demo method which shows how we can use PHP to parse XML, traverse nodes and extract data.
> Initial XMLMigrator class with a demo parsing method

- src/Migrator/General/XMLMigrator.php
- src/Migrator/PublisherSpecific/BethesdaMagMigrator.php
- src/Migrator/PublisherSpecific/CharlottesvilleTodayMigrator.php
Created a class which houses all of Bethesda's migration tasks.
> Bethesda Migrator

- src/Migrator/PublisherSpecific/BethesdaMagMigrator.php
This PR is to resolve [this issue](https://app.asana.com/0/1200980714215013/1202279767405691/f). The ACF plugin facilitated storage of a field named bm_subtitle. That needs to be transferred over to the post_excerpt field in the wp_posts table.
> feat: take ACF subtitle and transfer to post_excerpt.

- src/Migrator/PublisherSpecific/BethesdaMagMigrator.php
> feat: created a function that will process category changes from CSV.

- newspack-custom-content-migrator.php
- src/Migrator/General/PrelaunchSiteQAMigrator.php
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202830507045337
> Add PrelaunchSiteQAMigrator class scaffold

- src/MigrationLogic/Attachments.php
- src/Migrator/General/AttachmentsMigrator.php
This PR adds a command to use the Attachments utility method `get_broken_attachment_urls_from_posts` to get broken in-story image URLs.
The method was not checking [the responsive images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) using the`srcset` attribute from the `<img>` tag, this is fixed now.
The command can be used in batches to run it multiple times in parallel when the number of posts to check is high. It also accepts an `index` parameter in case the command is killed and you need to restart it from the last index.
I added a parameter to the `get_broken_attachment_urls_from_posts` method called `$logger` which is a callback function that we can use while looping over the posts, a use case for it, is to pass a function that will …
> feat(attachment): add command to verify broken images URLs

- src/Migrator/General/TaxonomyMigrator.php
Created a function which will sync the actual row counts from wp_term_relationships column to the wp_term_taxonomy.count column.
Another function in this commit is the ability to remove Tags with associated posts below a certain threshold.
> feat: created function to sync wp_term_taxonomy.count column.

- src/Migrator/General/PrelaunchSiteQAMigrator.php
I added an option to the menu to run all steps. This is to give The Knife users the ability to run all steps, since they can't provide flags to the command (at least not yet).
> Add option to run all steps

- src/Command/General/S3UploadsMigrator.php
Full example how to use the command given in `shortdesc`.
> Command to compare files in a local folder with files in a folder on S3.

- src/Command/PublisherSpecific/RetroReportMigrator.php
Fixes:
* Links imports
Adds:
* Video content formatter
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203641601421553
- https://app.asana.com/0/0/1203641601421539
> Retro Report Migrators

- src/Command/General/WooCommOrdersAndSubscriptionsMigrator.php
- src/Command/PublisherSpecific/RetroReportMigrator.php
- src/Logic/CoAuthorPlus.php
**IMPORTANT:** #258 should be merged first
Adds the importer for the "Education Events" content
> Retro Report education events import

- src/Command/General/ProfilePressMigrator.php
Reusable command which converts PP authors to GAs.
> PublishPress authors to Guest Authors

- composer.lock
Update composer.lock file and fix release
> fix(composer.lock): update composer.lock file

- newspack-custom-content-migrator.php
- src/Command/PublisherSpecific/LatinFinanceMigrator.php
Descriptions in Asana task.
Please push often, ideally on daily basis, and keep in mind that this code does not have to be perfect (it can contain dev comments, work in progress ideas, etc).
> Add/LatinFinance Migrator

- src/Command/PublisherSpecific/NewsroomNZ.php
- src/Logic/CoAuthorPlus.php
- src/Logic/SimpleLocalAvatars.php
Ensures that Guest Authors are imported rather than Users where necessary
Expands Author Fix command to look for GA or User
> Improve user import/author fixer

- newspack-custom-content-migrator.php
- src/Command/PublisherSpecific/DallasExaminerMigrator.php
See 1200550061930446-as-1204414060532245
> add Dallas examiner migrator

- newspack-custom-content-migrator.php
- src/Command/General/UsersMigrator.php
> feat(UsersMigrator): delete subscriber

- src/Command/PublisherSpecific/EfectoCocuyoContentMigrator.php
This adds a list of a few names found after the content refresh
> feat: update migrator with new names

- src/Command/General/CoAuthorPlusMigrator.php
- src/Command/PublisherSpecific/BethesdaMagMigrator.php
- src/Logic/CoAuthorPlus.php
- src/Utils/PHP.php
A command which converts WP_User to GA.
> Convert WP_User to GA

- src/Logic/MigrationMeta.php
- src/Utils/MigrationMeta.php
Keeping track of commands run and re-run should be easier with this.
> Add helper class for "migration meta".

- src/Command/General/EmbarcaderoMigrator.php
- Check the author page of a user that has an email as username and verify that the slug does not look like the email.
---
> EMB: Add user_nicename when adding users to get a nicer url

- src/Command/General/EmbarcaderoMigrator.php
Some of the older directories with photos don't have photos with `123_original.jpg` format. This PR tries some more file formats when finding media. It also uses the photo_name instead of the ID.
- I re-ran featured images, but anything that touches images should do. Maybe rename a file to xxx_full.jpg to see. 
- Take a look at the code.
> EMB: Try more file names for photos

- src/Command/General/EmbarcaderoMigrator.php
This will write a warn to the log if we only find a thumbnail for an image
> EMB: Warn if we only find a thumbnail

- src/Command/General/LedeMigrator.php
> dek postmeta to Subtitle

- src/Command/PublisherSpecific/LaSillaVaciaMigrator.php
The meta_values and post_ids in $target_data were found to be duplicate data. This command will look at the first and second post those IDs point to and copy over certain data points to the first post (post_date, post_date_gmt, and post_content). Then it will proceed to clean up the meta data by deleting the duplicate meta data point and ensuring that the first post is the only one that is pointed to using the `newspack_original_article_id` meta_key.
---
> fix: new command which addresses duplicate articles which were imported.

- composer.json
- composer.lock
- src/Utils/MigrationTemplater.php
Adds the (small) [PHP Mustache library](https://github.com/bobthecow/mustache.php) to the composer file. 
I've added a small wrapper to make loading templates from various directories simpler. The idea is that we have 2 places where `.mustache` templates can live:
**Publisher specific templates** live in `src/Command/PublisherSpecific/mustache-templates/<publisherName>` and can be used by calling `MigrationTemplater::format_publisher_html()`.
**General templates** live in `src/Command/General/mustache-templates` and should hold more re-usable stuff. 
* Run composer install
* Create a folder called HighCountryNews in the publisher folder mentioned above. Call it `test.mustache` and put it in the folder you just created. (this is just for testing so call it what you want, just adjust the …
> Add support for mustache templates

- src/Command/General/TownNewsMigrator.php
Those are handy for the url structure.
- Run the content migrator and verify in the GB sidebar that posts have a primary category.
> TN: Add a primary category

- src/Command/General/EmbarcaderoMigrator.php
Run the migration command and see the number of contributors in the users list increment.
> fix(EmbarcaderoMigrator): set authors as WP users when possible

- src/Command/General/CoAuthorPlusMigrator.php
- Run ` wp newspack-content-migrator co-authors-delete-all-co-authors` on a site with some Guest Authors. 
Also try with `--dry-run`.
- Verify that the authors went away using the UI or SQL or whatever works for you.
---
> Add command that deletes ALL Guest Authors

- src/Command/General/MigrationHelper.php
- src/Command/PublisherSpecific/HighCountryNewsMigrator2.php
- src/Logic/GutenbergBlockGenerator.php
This PR has the code used to run the re-import on HCN. It's all been run now, so I'm merging this one.
> Re-import HCN

- newspack-custom-content-migrator.php
- src/Command/PublisherSpecific/WindyCityMigrator.php
- src/Logic/GutenbergBlockGenerator.php
- src/Utils/Logger.php
This is a PR for a publisher migrator. I can provide a data sample on Slack :) 
This PR also fixes the `get_youtube` from the Gutenberg Block Generator where before the fix the method deleted the $_GET parameters, which was deleting the `v=video_id` parameter.
> feat(WindyCityMigrator): add migrator and fix YouTube GB block

- src/Command/General/EmbarcaderoMigrator.php
- Run this new command `newspack-content-migrator embarcadero-fix-more-posts-block`
- Check some posts from the logs that contain an aligned to the right Group Block that contains "More Posts" posts.
---
> fix(EmbarcaderoMigrator): fix More Posts block

- src/Command/General/EmbarcaderoMigrator.php
- Run the `newspack-content-migrator embarcadero-helper-fix-dates` with the parameters `index-from` and `index-to`
- Notice in the logs it's only running the batch we set
---
> feat(EmbarcaderoMigrator): add batching for cmd_fix_post_times

- src/Command/General/EmbarcaderoMigrator.php
This PR set media migration to always be true
---
> fix(EmbarcaderoMigrator): always migrate media

- src/Command/General/EmbarcaderoMigrator.php
- src/Utils/WordPressXMLHandler.php
> fix: fix bug with WordPressXMLHandler causing authors not to be set.

- src/Command/PublisherSpecific/HighCountryNewsMigrator2.php
There were some small changes to the JSON file format.
> HCN image handling changes

- composer.json
- composer.lock
- phpcs.xml
Thanks to @kariae for contribution, I'm just pushing ;)
> Upgrade coding standards

- src/Command/PublisherSpecific/WindyCityMigrator.php
This PR fix migrating galleries and add the feature of migrating PDFs for Windy City
---
> feat(WindyCityMigrator): migrate post's PDFs

- src/Command/PublisherSpecific/TheEmancipatorMigrator.php
Mainly author audit and image captions
> Tweaks to Emanciaptor

- src/Command/PublisherSpecific/HighCountryNewsMigrator2.php
They were somehow imported with made-up dates in the future.
> Fix dates on attachments

- composer.json
- composer.lock
Composer config updated to accommodate for scraper's new repo.
> Update Scraper new repo dependency

- src/Command/General/S3UploadsMigrator.php
- More accurate scaled image detection.
- Better descriptions, comments and nicer variable names
- Arguments extra check
- Sizes selection and confirmation improved
---
> S3 migrator: better scaled image detection and smaller improvements

- newspack-custom-content-migrator.php
- src/Command/PublisherSpecific/BigBendSentinelMigrator.php
Initial commit for migrator.  Ron will be adding a converter for People CPT to Guest Authors.  Task in Asana - via Megan.
cc @iuravic
> Add / Big Bend Sentinel Migrator

- composer.json
- composer.lock
- newspack-custom-content-migrator.php
- src/Command/General/CreativeCircleMigrator.php
- src/Command/PublisherSpecific/CityViewMigrator.php
This adds a generic CC importer and one for CityView using the generic as much as possible.
> Add CC commands and Cityvew

- src/Command/PublisherSpecific/WindyCityMigrator.php
Add a command that _slowly_ chews it's way through all posts replacing broken entities with actual char values. Yay UTF8.
> Fix broken/odd HTML entities in WCN

- src/Command/General/EmbarcaderoMigrator.php
> Detailed logging to CSV

- src/Command/PublisherSpecific/LaSillaVaciaMigrator.php
This command fixes content that have base64 images encoded in `<img src=` attributes.
---
> fix: content w/ base64 images encoded in content prevent Yoast indexing

- src/Command/General/EmbarcaderoMigrator.php
This script corrects comments that were incorrectly assigned to posts. It also creates a QA file for deleted comments for review.
---
> fix: new command to correct comments on posts for Embarcadero

- src/Command/PublisherSpecific/TheFriscMigrator.php
- src/Logic/GutenbergBlockGenerator.php
This adds a fixer for blocks that were converted wrong by the NCC. It makes Twitter blocks work again.
---
> Fix more content in Frisc

- src/Command/General/MediumMigrator.php
> Create a warning for wrong image import

- newspack-custom-content-migrator.php
Simply includes the CC migrator.
> Include CC migrator

- src/Command/General/CreativeCircleMigrator.php
Try adding `--content-type=photos` for instance to get other content than just the Stories.
> Add content type support in the scraper

- tests/data_providers/gutenberg_blocks.php
Delete hardcoded unclaimed S3 bucket name
---
> fix(GutenbergBlocks): delete hardcoded S3 bucket name

- src/Command/PublisherSpecific/ArkansasTimesMigrator.php
A small fix that changes the meta used to create an Issue -> Thumbnail relationship.
---
> Arkansas Times: Fix thumbnail meta source reference

- src/Command/PublisherSpecific/ArkansasTimesMigrator.php
- src/Logic/GutenbergBlockGenerator.php
YouTube Block is broken if the source URL contains query parameters, we need to clean the URL before using it in the block
---
> fix(GutenbergBlockGenerator): fix YT block

- newspack-custom-content-migrator.php
- src/Command/PublisherSpecific/ZocaloMigrator.php
> Import post authors and sub titles

- publisher-specific-archive/BeaconSitesMigrator.php
> New simpler PR version from original PR#444

- publisher-specific-archive/MinnPostMigrator.php
> Duplicate of PR#387

- publisher-specific-archive/LookoutLocalMigrator.php
Publisher specific file from https://github.com/Automattic/newspack-custom-content-migrator/pull/324 to archive.
> Copy of #324

- newspack-custom-content-migrator.php
- publisher-specific-archive/AfroMigrator.php
- src/Command/General/PaidMembershipsPro2WooCommMigrator.php
New version of old https://github.com/Automattic/newspack-custom-content-migrator/pull/159 in order to minimize impact on new trunk in regards to merge conflicts and autorship changes.
> Archive migrator for Afro with PaidMembershipsPro to WC migrator

- publisher-specific-archive/LatinFinanceMigrator2.php
> Old migrator added to publisher archive from old PR#298

- .github/workflows/update-nmt-dependency.yml
I need to merge this to test properly – will make a second PR to test the action.
> React on update dispatch from the NMT

- src/Command/PublisherSpecific/ZocaloMigrator.php
Some last minute changes to the author handling.
This already ran
> Add fixes to zoc  migrator

- newspack-custom-content-migrator.php
- src/Command/PublisherSpecific/RoughDraftAtlantaMigrator.php
Publisher specific migration commands,
- set all posts' categories under a custom given top category
---
> thegavoice merging into roughdraftatlanta

- src/Command/General/EmbarcaderoMigrator.php
> fix: various helper scripts to help untangle the mess that was Authors import for Embarcadero.

- newspack-custom-content-migrator.php
- src/Command/PublisherSpecific/County17Migrator.php
Publisher specific migrator for County 17 with helper methods/commands.
---
> Publisher specific migrator County17
