cli_scripts/inc/functions.sh
cli_scripts/update_recipes/0_UPDATE_RECIPE_TEMPLATE.sh
src/Migrator/General/AdsMigrator.php
src/Migrator/General/CampaignsMigrator.php
src/Migrator/General/ContentConverterPluginMigrator.php
src/Migrator/General/CssMigrator.php
src/Migrator/General/ListingsMigrator.php
src/Migrator/General/MenusMigrator.php
src/Migrator/General/NewslettersMigrator.php
src/Migrator/General/PostsMigrator.php
src/Migrator/General/ReaderRevenueMigrator.php
src/Migrator/General/ReusableBlocksMigrator.php
src/Migrator/General/SettingsMigrator.php

Cleans up and simplifies the Update Recipe structure and output:
- [renames historic VaultPress wording to Jetpack](https://github.com/Automattic/newspack-custom-content-migrator/commit/8ee75a4a847557e0db7c1c8393067d301a19a5bd)
- [removes unnecessary if-s](https://github.com/Automattic/newspack-custom-content-migrator/commit/0e0153d3232c68902c1e2fdfc6e53618ff33b51e)
- [removes one-liner functions](https://github.com/Automattic/newspack-custom-content-migrator/commit/e5c530998a94a0716ef52378db1674ea81dedb5e)
- [simplifies config variables](https://github.com/Automattic/newspack-custom-content-migrator/commit/500a24c26279accf21b2113fa78bf28af254bdce)
- [`search-replace` is now used if found locally, and downloaded only if not](https://github.com/Automattic/newspack-custom-content-migrator/co …

Clean up Update Recipe

---

newspack-custom-content-migrator.php
src/Migrator/PublisherSpecific/ElLiberoMigrator.php

El Libero has custom post_types for posts. These need to be migrated so that the post_type = post. This is so that all posts will be visible on their site. The custom post_type's have been migrated to be categories instead.

feat: creating migrator for el libero posts.

---

newspack-custom-content-migrator.php
src/Migrator/PublisherSpecific/PublicIntegrityMigrator.php

Migrates authors from ACF5 terms to ACF co-authors, and set them to their posts.

feat: add Public Integrity ACF to CAP authors exporter

---

src/Migrator/PublisherSpecific/VoiceOfSanDiegoMigrator.php

This add posts authors checker between the live version of Voice of San Diego posts and the previous live version.
I used the same way to validate posts authors for another publisher.
This is useful when noticing a bylines mismatch after doing a content migration. The code is easily customizable to be used for other publishers if needed.
CC @iuravic @eddiesshop

feat(Voice of San Diego): Add authors checker.

---

newspack-custom-content-migrator.php
src/Migrator/PublisherSpecific/ElLiberoCustomCategoriesMigrator.php
src/Migrator/PublisherSpecific/ElLiberoMigrateMissingUsers.php

This PR will address an issue whereby certain users were not copied to the wp_users table from the live_wp_users table via the content diff approach. This is because El LIbero handles users differently from most of our other publishers. They create users on their platform to allow them to see gated content. This PR identify the users that were not copied over and bring them over to the wp_users table as well as handle their metadata.
CC @iuravic @kariae

Will go through users in live_wp_users and copy them to wp_users for EL.

---

newspack-custom-content-migrator.php
src/MigrationLogic/NinjaTables.php
src/Migrator/General/NinjaTablesMigrator.php

This PR proposes a bulk exporter for the tables created with NinjaTables.
A first attempt to do this was by doing it manually (querying the tables ...) but I switched to use the same way we use with other migratory which is using the plugin already made classes/methods. So in order to work, the command needs the NinjaTables plugin to be installed.
As of now, there is only one command that does the bulk import if needed in the future we can add a parameter or a second command to export a specific table.
The command export to either CSV or JSON files (default to CSV). Below are a few examples to use the command:
```bash
wp newspack-content-migrator export-ninja-tables --output-dir=/tmp
wp newspack-content-migrator export-ninja-tables --output-dir=/tmp --output-type=json
```
@iuravic …

Feat: NinjaTables exporter

---

newspack-custom-content-migrator.php
src/MigrationLogic/TablePress.php
src/Migrator/General/TablePressMigrator.php

This PR introduces a bulk tables importer to TablePress. It accepts CSV and JSON files from a given folder.
It uses the filename as the table name and the first row of data as the table header (same as the GUI importer of TablePress).
Since the import command uses the internal classes/methods of the plugin TablePress, the plugin should be installed before using it.
Below some examples to use the command line:
```bash
wp newspack-content-migrator import-table-press-tables --input-dir=/tmp
wp newspack-content-migrator import-table-press-tables --input-dir=/tmp --input-type=json
```
The code introduces a new migrator logic class so it needs a review 🙇

Feat: TablePress importer

---

newspack-custom-content-migrator.php
src/Migrator/PublisherSpecific/EnergeticCityMigrator.php

They require featured images to be fixed. Doing this via PHP makes it much easier.
I am searching for rows in wp_posts with post_type = 'attachment' and post_title LIKE 'https://media.socastsrm.com' which seems to have been systemically brought in via XML import. I am then parsing the URL to obtain the file name which seems to correspond to the post it was the featured image for. If that original post is found, then I will delete any previous featured images and create a new row that attaches the found featured image.

feat: creating a migrator for EnergeticCity.

---

src/Migrator/PublisherSpecific/RevealMigrator.php

This PR uses the posts iterator from #149.
This publisher has their posts credits as posts meta and needed to have them on the post body to be able to edit and show them.

feat(RevealMigrator): migrate post credits from meta to the post content

---

newspack-custom-content-migrator.php
src/Migrator/PublisherSpecific/BethesdaMagMigrator.php

This is a simple command that detects duplicated posts and pages and deletes them for Bethesda Mag.
This probably can be refactored to be used globally.

feat(Bethesda): delete duplicated posts and pages

---

src/Migrator/PublisherSpecific/IthacaVoiceMigrator.php

@iuravic @eddiesshop, a quick fix for the posts loop for Ithaca Voice galleries migrator, I forgot the `post__in` argument that was there to test the migrator, I'll skip the PR review for this one.

fix(Ithaca Voice): fix the galleries migrator loop to go over all the posts

---

newspack-custom-content-migrator.php
src/Migrator/General/AttachmentsMigrator.php

I encountered a case where I needed to list IDs of locally stored attachment images by years. I was then able to regenerate thumbnails year by year (before uploading them to S3), because regenerating all the thumbnails on the entire site filled up the disk all the way. 
Sharing here the initial version of this command. Possibly to be improved/extended in the future.

Lists local attachments IDs by years

---

src/MigrationLogic/ContentDiffMigrator.php
src/Migrator/General/ContentDiffMigrator.php

Content importer should only update the newly imported Posts' att.ID, not modify the existing Posts' attachment IDs. This PR fixes that.
This bug wasn't visible previously, because it only affects external sites which use same attachment IDs that also exist on the Staging site. An example such as this is most apparent in completely separate content archives, like additional archive sites with completely separate contents, but would not be visible if a preexisting content on Staging (like Newspack pages) didn't use the same IDs, and if it didn't use featured images (attachment IDs).
An example:
- if a Staging has an existing Post 111 with attachment 123,
- and the external archive site ("live DB") has another Post 33333 with same attachment ID 123 (but this is a different attachment file), …

A fix for Content Diff updating of Attachment IDs

---

src/MigrationLogic/Attachments.php
src/Migrator/General/AttachmentsMigrator.php

This PR adds `get_broken_attachment_urls_from_posts` method to the `Attachments` logic class, it returns broken URLs indexed by post IDs. 
The function takes into consideration the usage of [s3_uploads](https://github.com/humanmade/S3-Uploads) plugin which switches the image URL on the fly when we're rendering the post frontend (with `the_content` filter).
This can be used in something like this:
```php
use \NewspackCustomContentMigrator\MigrationLogic\Attachments as AttachmentsLogic;
// ...
$result = $this->attachments_logic->get_broken_attachments_urls_from_posts_content();
// $result = $this->attachments_logic->get_broken_attachments_urls_from_posts_content( [ 443372, 440745 ] );
foreach($result as $post_id => $broken_urls) {
$post = get_post($post_id);
$updated_post_content = …
```

detect broken attachments URLs in posts content

---

src/MigrationLogic/ContentDiffMigrator.php
src/Migrator/General/ContentDiffMigrator.php

This body of work will detect if table collations are different between live and core WP DB tables. If they are, this work will be able to execute a set of instructions to correct the discrepancy. This will then allow the content-diff to proceed correctly.

feat: prevent content-diff from erroneously declaring no posts to refresh.

---

src/Migrator/General/S3UploadsMigrator.php

Some S3 integration plugins use custom subfolders for images, e.g. 
```
uploads/YYYY/MM/CUSTOM_SUBFOLDER/img.jpg.
```
This commands moves the files down a level to 
```
uploads/YYYY/MM/img.jpg
```
This is refactored from [CharlestonCityPaperMigrator](https://github.com/Automattic/newspack-custom-content-migrator/blob/master/src/Migrator/PublisherSpecific/CharlestonCityPaperMigrator.php#L82) from a year ago, and is an initial commit for the command.
Future improvements:
- the command only moves the files out of the subfolders down a level below into the MM folder, but keeps the custom subfolders -- those can be deleted after the move

Moves files out of those custom S3 integration subfolders in uploads

---

src/MigrationLogic/ContentDiffMigrator.php

There is an error in our new fix collation command when fixing live tables' collations in case where the source table has a different number of columns from the destination table.
Here's a screenshot I got after running the command, it shows no errors, and looks like everything worked well:
But the `live_wp_users` did not get any of the users inserted, while the`bkp_live_wp_users` had 66 users.
Firstly I added [this error handling](https://github.com/Automattic/newspack-custom-content-migrator/pull/198/files#diff-318440e2d6c2a49e7dc183f0e2590ace80e9984dff1602b43286cfc85eca0133R1561) which checks the return from the insert statement in more details. The return in this example was false, and `! is_wp_error` didn't catch it. I added the SQL which failed to the exception message, too, for …

Catch and fix insert error on collation fix

---

newspack-custom-content-migrator.php
src/Migrator/PublisherSpecific/LkldNowMigrator.php

I created a new migrator for Lkldnow under Migrators/PublisherSpecific called LkldNowMigrator. I also added a command that migrates the users' avatars to Simple Local Avatars. It's related to this [ticket](https://app.asana.com/0/1201792624707312/1202733251254639).

Add migrator for Lkldnow + Command for migrating avatars

---

newspack-custom-content-migrator.php
src/MigrationLogic/CoAuthorPlus.php
src/Migrator/General/XMLMigrator.php
src/Migrator/PublisherSpecific/ColoradoSunMigrator.php

Adds a couple of [reusable `src/MigrationLogic/CoAuthorPlus.php`](https://github.com/Automattic/newspack-custom-content-migrator/pull/189/files#diff-c611c751d7c038cdc139659e6c97c7cbf8e95ec726b278e1d3786ba94c7aa1b4) methods:
- `NewspackCustomContentMigrator\MigrationLogic\CoAuthorPlus::get_guest_author_by_display_name()`
- `NewspackCustomContentMigrator\MigrationLogic\CoAuthorPlus::get_posts_existing_ga_ids()`
Publisher specific functionality, several commands in the new PubSpecificMigrator class.

Colorado Sun data migrator

---

src/Migrator/General/ContentDiffMigrator.php

Besides saving Live site's old Post object IDs in log file, now saving these as postmeta called `newspackcontentdiff_live_id`.

Saves old post ID as meta

---

src/Migrator/PublisherSpecific/LkldNowMigrator.php

I created this command for this [ticket](https://app.asana.com/0/1201792624707312/1202664404571760). All it does is take the original's content link and name from the 'aalink' and 'aaname' custom fields, and add a paragraph to the end of each article with a link to that original article.
I also made the script `sleep` every 100 posts to avoid any issues with the database.

Add command to migrate republished content from meta to paragraphs

---

src/MigrationLogic/Posts.php
src/Migrator/General/AttachmentsMigrator.php

This PR improves the delete attachments command and renames it from `attachments-delete-posts-images` to `attachments-delete-posts-attachments` because it deletes all attachments, not only images.
The attachments marked to be deleted are no longer checked, which improves performance.
Skip the media used in the widgets from deletion.

Improve delete attachments command performances

---

src/MigrationLogic/SimpleLocalAvatars.php

I added the wrong meta key to the `AVATAR_META_KEY`. Creating this PR to fix it. I will push directly to master since it's a simple typo fix.

Fix avatar meta key

---

src/Migrator/General/S3UploadsMigrator.php

\readline() seems to have gone missing from Atomic recently. This adds it back to this migrator so we can use it.
@abdelmalekkkkk , I'm not a 100% sure if you were researching this same functionality as \readline(), but perhaps we could add this code somewhere more reusable, if it would be of use to other Migrators too.

Add missing function readline

---

src/MigrationLogic/Posts.php
src/Migrator/General/PostsMigrator.php

Adds 3 CLI commands:
`newspack-content-migrator find-posts-by-number-of-revisions [$number_of_revisions=500]` 
Looks for posts with more than a certain number of revisions. (Default 500). Example:
```
$ wp newspack-content-migrator find-posts-by-number-of-revisions
+---------+--------------------------+
| post_ID | num_of_revisions |
+---------+--------------------------+
| 145     | 2345                        |
| 196     | 1023                        |
+---------+--------------------------+
```
`newspack-content-migrator clear-revisions [$number_of_revisions=500]`
Looks for posts with more than a certain number of revisions using the command above and then delete them.
`newspack-content-migrator clear-post-revisions $post_ID [$number_of_revisions=500]`
Deletes the revisions of one …

Add revision cleaning commands

---

src/Command/General/ContentDiffMigrator.php

Two changes:
1. the `newspack-content-migrator content-diff-search-new-content-on-live` now displays a list of all the CPTs in the DB, and allows searching for custom CPTs
2. the `newspack-content-migrator content-diff-migrate-live-content` seamlessly imports CPTs
Also includes very small refactoring of some command code to avoid duplication.

Content Diff support for CPTs

---

src/Command/General/TaxonomyMigrator.php
src/Logic/Taxonomy.php

The command "sync-taxonomy-count-with-real-values" did not fix counts for categories which should have zero count.
Fixed and rewrote the command from using a complex DB query to use the built in WP `wp_update_term_count_now()`.
Renamed command `sync-taxonomy-count-with-real-values` to `fix-category-and-tag-count`.
Added a new command `fix-taxonomy-count` which can fix any other taxonomy count.
Also ran PHPCS and fixed some things, but not all of them.

Fix for "sync-taxonomy-count-with-real-values" command

---

src/Command/General/TaxonomyMigrator.php
src/Logic/Taxonomy.php

Can take any category tree (parent category and all the children categories), and relocate/replant that category tree under a different parent.
Before:
After:
As the title says, moves all the posts from one category to a different one.

Category moving functionality for Outlier/Detour Detroit

---

src/Command/General/ContentDiffMigrator.php
src/Logic/ContentDiffMigrator.php
src/Utils/PHP.php

Checks if any of the posts on Staging were modified on Live with a greater `post_modified` date, and it then reimports them.
How to test:
- mysqldump of "live site" which has a few posts that have `post_modified` > `post_modified` on Staging; import those tables with `live_` prefix side by side to the local "staging" DB
- run the `newspack-content-migrator content-diff-search-new-content-on-live` command and check that the new `content-diff__modified-ids.log` gets created with those IDs
- run the regular Content Diff import command, and check that the Posts have been updated

Content Diff refresh modified posts

---

src/Command/PublisherSpecific/RetroReportMigrator.php
src/Logic/CoAuthorPlus.php

Add the Articles importer, including:
* improvements to the video importer and markup generator for easy lookup of imported videos.
* handling for multiple authors.
* block handling.
Also introduces a new reusable CAP helper, `get_or_create_guest_author_from_user()` to allow importers to easily get or create guest authors from a given WP User.

Retro Report articles import

---

src/Command/General/WooCommOrdersAndSubscriptionsMigrator.php

The following deprecated notice appears several times when running commands in the migrator:
> PHP Deprecated:  Required parameter $table_prefix_source follows optional parameter $source_order_id in /var/www/html/wp-content/plugins/newspack-custom-content-migrator/src/Command/General/WooCommOrdersAndSubscriptionsMigrator.php on line 152
This change adds default values to the last two parameters of the `migrate_order_or_subscription()` function in order to satisfy the requirement in later versions of PHP.

Fix for Deprecated notice in WooCommOrdersAndSubscriptionsMigrator.php

---

src/Command/PublisherSpecific/NewsroomCoNzMigrator.php

Adds a WP CLI script for `1200550061930446/1204502855407758`. Queries all posts that start with a bolded and italicized paragraph (NZ's standard format for subtitles) and moves those paragraphs to the `newspack_post_subtitle` meta field instead.
To test, ensure you have some posts whose first block is a paragraph containing bolded + italicized text. run `wp newspack-content-migrator newsroomconz-migrate-subtitles`. Supports a `--dry-run` flag to print changes without persisting.
Hint: a lot of whitespace changes from my IDE, so disable whitespace changes to see the true changeset.

add: Newsroom NZ migration script for subtitles

---

newspack-custom-content-migrator.php
src/Command/General/CoAuthorPlusMigrator.php
src/Command/General/InlineFeaturedImageMigrator.php
src/Command/General/MetroMigrator.php
src/Command/PublisherSpecific/VTDiggerMigrator.php
src/Logic/ContentDiffMigrator.php
src/Logic/Posts.php
src/Logic/Taxonomy.php

Besides publisher-specific code, here merging a couple of general type contributions:
- src/Command/General/InlineFeaturedImageMigrator.php, `newspack-content-migrator hide-featured-image-if-used-in-post-content` command
- updated this command so that **by default it hides the featured image only if post_content starts with that image**
- added optional flag `--anywhere-in-post-content`, which will not hide featured image just if post_content **begins** with that image, but also if that image is used **anywhere** in post_content
- added `dry-run` flag
- ContentDiff logic class -- fixed some warnings (they were caused because some Gutenberg blocks (for example wp:image) have the `id` attribute, but some don't -- if image is inserted from remote URL, not from Media Library)
- Taxonomy logic …

VT Digger, launch updates

---

src/Logic/ContentDiffMigrator.php

Explanation -- when CDiff merges categories from live site to staging, it recreates the whole category tree from live on staging. It used to match/search a categories by its "name", "parent term_id" and "description".
But on some sites, category "description" gets changed on Live during migration, which broke category matching/searching back on Staging.
Now excluding category's "description" from category matching/searching, and category is identified by its "name" and "parent term_id".
In retrospect, checking for category "description" was an overkill and really unnecessary, buy now it's also causing issues. Even though we predicted that category changes wouldn't be made during migration, it happens sometimes since it's out of our control.
The new method …

CDiff recreate categories by name and parent term_id, skipping category description

---

newspack-custom-content-migrator.php
src/Command/General/ContentDiffMigrator.php
src/Logic/ContentDiffMigrator.php

Not waiting for a full PR review for this one because it only improves message outputs.
Sometimes live DBs are faulty -- for example, there could be invalid term_relationships, or completely missing terms. Nothing we can do in that case, and warnings must happen.
Previous warnings were very general. This now outputs more verbose warnings on screen, but at least it's clearer that it's an error in Live DB, not in Content Diff code.
Example before:
Example after:
Though more verbose, we can immediately see that it's a "faulty term_relationship record in live DB".
Perhaps we could even skip outputting warnings completely for these? If you think so, please share and we can hide them in the future.

More verbose import warnings on CLI output

---

newspack-custom-content-migrator.php
src/PluginSetup.php

This is a purely dev plugin and we want to see all warnings on screen.
Sometimes when running my own or others' code, I find missed warnings that end up only in debug.log, and author (me or someone else) hasn't noticed them.
This ensures all warnings and errors get output to screen and logged to debug.log on plugin-run-level.

Config plugin to dev debugging and error display level

---

src/Command/PublisherSpecific/RetroReportMigrator.php

I had a wrong namespace in the `use` statement in #328

Fix namespace in use

---

src/Utils/Logger.php

This also does not exit on WP_CLI::error. Before it would.

Log before exiting and prepend log level in file

---

src/Logic/Attachments.php

This fixes an edge case in `import_external_file()` where files would not get imported if the url (or file path) they are on does not have a file extension. It uses the mime type to try to sniff out what kind of file it could be. Not 100% good but a lot better than importing 0%

Try to guess the file extension for external file downloads without one

---

src/Logic/Attachments.php

This adds a function that checks if we already have an upload to the media library of a given file.
The file to check needs to be in the filesystem (like we don with tmp files in `import_external_file()` in `Attachments.php`).
The idea is to check if we already have a file uploaded by getting file(s) from the media library with the same filename and then checking to see if a file has:
* The same file size 
* The same hash of the file content
We talked about this one in Slack: p1693569468634049-slack-C013N9S2C7Q

Try to find an existing file in the ML when adding external files

---

newspack-custom-content-migrator.php
src/Command/General/DownloadMissingImages.php
src/Command/PublisherSpecific/LaSillaVaciaMigrator.php
src/Logic/Attachments.php
src/Logic/Posts.php

This downloads missing images and is probably re-usable for other sites in the future.
I pulled most code into a new file because there ended up being a lot of it :)
Run it with `wp newspack-content-migrator la-silla-vacia-download-missing-images --media-dir="../path/to/medi" --post-id=5325` and post id is optional.

Download missing images

---

newspack-custom-content-migrator.php

Super simple PR -- removes one line from main plugin file.
WP Importer should not always be installed and activated every time this plugin is used.

Do not always install WP importer

---

newspack-custom-content-migrator.php
src/Command/General/EmbarcaderoMigrator.php
src/Logic/GutenbergBlockGenerator.php

@Automattic/newspack-launch-and-infrastructure an FYI for the second part of the Embarcadero sites migrator, it contains commands to migrate post comments and print issues. It also add a method to the GutenbergBlockGenerator to generate File Block (with a PDF previewer).

Add/embarcadero migrator part II (post comments and print issues)

---

newspack-custom-content-migrator.php
src/Command/General/LedeMigrator.php
src/Logic/ContentDiffMigrator.php
src/Logic/Lede.php

Lede custom Authors migrator to GAs:
- a command `lede-migrate-authors-to-gas`, which also takes `--live-table-prefix` argument (value e.g. `live_`), because it needs to know which were the old IDs of Posts **and Users**
Content Diff, slipped in a connected small addition:
- added saving meta "old ID" for imported WP_Users

Capital B and Lede Authors custom plugin migrator

---

src/Command/General/EmbarcaderoMigrator.php

The main import command `cmd_embarcadero_import_posts_content` uses optional `--index-from` and `--index-to` arguments. If these are omitted command should import all the records (useful if running on local). If these optional arguments are used, [these lines](https://github.com/Automattic/newspack-custom-content-migrator/pull/356/files#diff-63741758e19aeef0bc3caad7975625f46c2000cc08706d5e639bf97e61365309L414-L417) ("// Get selected posts.") will make sure only the selected records index-from and -to will be imported.
But there is also the `if ( 2000 === $post_index ) { break; }` which is removed by this PR. These lines will disable importing all records at once (if index-from and -to are not used) and will exit after 2000. We don't need this block, removed by this PR.
- no need to test …

Remove breaking exit

---

src/Command/General/EmbarcaderoMigrator.php

- Command `embarcadero-migrate-comments` now imports comments even if coment's user is not found (WP accepts comments without a WP_User attached to them)
I also added a helper command with a workflow which helped me fix a broken CSV for Pleasanton. It's a bit elaborate/specific, but it does the trick. I tried several variations, and this one worked:
- Added the helper command `embarcadero-helper-fix-tsv-file` which helps fix broken CSVs. I've shared how it's used up in the comments at the top of the class -- see "How to fix CSVs if migrator reports that some rows can't be read":
1. convert CSV to TSV using OSX Pages. I first converted CSV to TSV this because commas are a part of the problem, and tab-separated-values bypass all that. Also everyone from our Team has Pages and it works well …

Embarcadero Migrator, import comments wo/ user, and smaller updates

---

newspack-custom-content-migrator.php
src/Command/PublisherSpecific/MustangNewsMigrator.php

Mustang News: Command to move image credit from posts to attachments

---

src/Logic/Attachments.php

Also add a wrapper for file import that enforces a post id to attach it to. This should keep a neater organization into year folders in upload.
I also added one more extra check so we get fewer file not found errors.
It helps to import a file which has a different extension (e.g. .blob instead of .jpeg, missing .pdf, etc).
- try calling both `import_external_file()` and `import_attachment_for_post()` including the `$desired_filename` argument on a file that you've changed the file extension to something like `.notallowed` and verify that you get the file downloaded correctly.
---

Fix the "Sorry, you are not allowed to upload this file type." error

---

src/Command/General/EmbarcaderoMigrator.php

This fixes dates to use the correct timezone. 
Note: the WP site should be set to the 'America/Los_Angeles' timezone if this should be run. Let's discuss if that is a problem for the sites that don't have that currently.

EMB: Fix timezones

---

newspack-custom-content-migrator.php
src/Command/General/MigrationHelper.php

Inspired by frustration with internet connection cutting out and trying to navigate running scripts with `start` and `end`. It's super hard to keep track of what ran and what didn't in that case.
This thingy doesn't run anything, but outputs a bunch of commands that can be pasted in a file and then run one by one or in multiple terminals. 
- With some command that supports `from` and `to` run like this:
```bash
wp newspack-content-migrator migration-helper-output-batched \
"wp newspack-content-migrator some-command --some-arg=horse --other-arg=goat" \
--total-items=122 --batch-size=60
```
- You need to know how many items you are running (or choose a random number high enough). 
- If your command doesn't use the `BatchLogic` class, you can pass the name of the `from` and `to` like this: …

Helper to make batching easier

---

src/Command/General/MigrationHelper.php

This is a tiny fix that I'll merge in a sec.
It adds more whitespace to the MigrationHelper batch outputter to aid readability.
- It's purely visual
---

Add missing newlines

---

src/Logic/CoAuthorPlus.php

- No test needed, this add a parameter that already exists in the used `get_guest_author_by` from the CAP plugin.
---

feat(CoAuthors): allow disabling CAP cache when getting linked authors

---

src/Logic/GutenbergBlockGenerator.php

Retreived posts by $wpdb get their IDs as strings, if we pass this to get_image it generates a broken image block, this makes sure the ID is a number.
---

fix(GutenbergBlockGenerator): make sure the attahcment ID received is a number in get_image

---

src/Logic/Attachments.php

- Upload an image with a special character in the filename (e.g. `1*test.jpeg`) using the `import_external_file` method two times and notice that the image is duplicated in the media library.
- Pull this and redo the previous  step and notice that the media is not duplicated this time.
---

fix(Attachment): sanize filename before search query

---

src/Logic/GutenbergBlockManipulator.php

This adds a class that can remove/replace/search/filter etc GB blocks. It only has what I needed for a specific migration, and we can certainly add more as we go.
- The functions should do what they say – you will likely need to write some test code to run them - or look at the code :) 
---

Add re-usable class for blocks manipulation

---

composer.json
composer.lock

This library was promising, but ended up causing more trouble than helping. This removes it. `simplehtmldom\HtmlDocument` ended up being the way to go.
---

Remove unused html purifier library

---

src/Utils/CsvIterator.php

This adds a CSV iterator a lot like the JsonIterator we already have. It uses BatchLogic args so it should be easy to use without having to do math.
Test that all lines are read correctly passing in nothing, `--start=x` and/or `--end=x`.
Use a .csv file something like this:
```php
$csv_file_path = $assoc_args[ $this->csv_input_file['name'] ];
$batch_args = $this->csv_iterator->validate_and_get_batch_args_for_file( $csv_file_path, $assoc_args, ',' );
$counter    = 0;
foreach ( $this->csv_iterator->batched_items( $csv_file_path, ',', $batch_args['start'], $batch_args['end'] ) as $row ) {
}
``` 
To use the BatchLogic, register a command something like this:
```php
private array $csv_input_file = [
'type'        => 'assoc',
'name'        => 'csv-input-file',
'description' => 'Path to CSV …
```

Add a CSV file iterator that uses the BatchLogic

---

src/Command/General/TaxonomyMigrator.php

I had some shortcodes and other stuff get migrated into category descriptions using `convert_term_to_category()`. This just escapes it.
Probably enough to just eyeball the code :)

Taxonomy Migrator: Sanitize text added to category descriptions

---

src/Logic/Attachments.php

Using `wp_get_mime_types()` to get the mime type  of an image returns `jpg|jpeg|jpe` as a key to the JPEG mime type instead of one extension, which breaks `media_handle_sideload` since we'll be uploading a file with a `name` ending with `file_name.jpg|jpeg|jpe`. This is a little fix for it.
- Use `import_external_file` to upload a JPG image with a filename that doesn't contain the extension.
- Notice the upload is not working.
- Apply the patch and re-run the import.
- Notice that the upload is working.
---

fix(Attachments): fix extension of images without one

---

newspack-custom-content-migrator.php
src/Command/General/RasMigrator.php

This is useful to skip the last step of the RAS wizard, that consists of configuring each Campaign Prompt from the defaults we offer.
With this command you can instead import campaigns from a json file exported from a site used as a model, and then programatically go through that last step on the checklist.
In the future we can expand this migrator to programatically go through other steps in the RAS wizard.
- Take a site with many prompts and segments and export its contents `wp newspack-popups export --file=newspack-campaigns.json`
- Put this json file in an publicly accessible URL
- Go to another brand new site and go through the RAS wizard until the last step "Reader Activation Campaign" - Don't complete this last step
- Run this command: `newspack-content-migrator …

feat: add general ras migrator

---

src/Command/General/EmbarcaderoMigrator.php

This PR fixes broken URLs migrated in content and migrates text styling.
- Search in the database posts you migrated with broken migrated URLs `post_content like '%>http<%'`.
- Check the post frontend and notice that the article contains some URLs with `http` as text.
- Get the post-original ID from the database using the meta `_newspack_import_id`.
- Add a condition around line 547 to migrate only that post (only for test purposes), something like:
```php
if ('123456' !== $post['story_id'] ) {
continue;
}
```
- Run the migrator with the flags `--refresh-content --skip-post-media` to refresh the content without downloading the images.
- Recheck the post and notice that the URLs are fixed.
- Do the same for the text styling tags:
- Italic: `post_content like '%==I%'`
- Bold: `post_content …

fix(EmbarcaderoMigrator): add text styling and fix broken URLs in content

---

src/Logic/Medium.php

This PR sets the Medium's posts migrated tags as categories instead of post tags. Since Medium doesn't have the notion of categories and we use categories for our articles structure instead of tags.
- Get a Medium export, I can provide that.
- On an empty WP site, run the migration command `wp newspack-content-migrator migrate-medium-archive --zip-archive=/path/to-the/archive/file.zip`
- Notice the list of tags in the dashboard is empty.
- Notice the list of categories containing some new ones, that are linked to the imported posts.
---

feat(MediumMigrator): set tags as categories

---

src/Command/General/EmbarcaderoMigrator.php
src/Utils/Logger.php

This PR adds a QA command to run on the Embarcadero sites post-launch:
```shell
wp newspack-content-migrator embarcadero-post-launch-qa \
--story-csv-file-paths=/new_export/story.csv,/old_export/old_files/story.csv,/new_export/story_1.csv,/old_export/old_files/story_1.csv \
--story-photos-file-paths=/new_export/story_photos.csv,/old_export/old_files/story_photos.csv \
--story-media-file-paths=/new_export/story_media.csv,/old_export/old_files/story_media.csv \
--story-carousel-items-dir-paths=/new_export/story_carousel_items.csv,/old_export/old_files/story_carousel_items.csv
```
It also adds the `INFO` level for the logger :)
---

Feat/embarcadero add QA command

---

src/Logic/Attachments.php
src/Logic/GutenbergBlockGenerator.php

This to avoid CDN urls in migrations
On a site that is connected to Jetpack, first run this to verify that you get a cdn url:
`wp eval "var_dump(wp_get_attachment_image_src( 71044, 'full'));"`
Then test the new function that wraps:
` wp eval "var_dump(\NewspackCustomContentMigrator\Logic\Attachments::get_attachment_image_src( 71044, 'full'));"`
you should now _not_ be getting a CDN url. 
We can likely use this function from more places than the Block Generator where I wanted it fixed, but let's start with this.
---

Add and remove filter in wrapper for image urls

---

newspack-custom-content-migrator.php

This simply removes some publisher migrators that are done.

Remove a few unused migrators from inclusion

---

newspack-custom-content-migrator.php
src/Command/General/PostDateMigrator.php

- Create a post (or edit one in the DB) to have a date in some timezone
- Run converter
- Check that the timezone was fixed.
Run like this for example: 
`wp newspack-content-migrator change-posts-timezone --from-timezone=UTC --target-timezone='America/Chicago' --num-items=500`
---

Add a command to fix posts imported with wrong timezone

---

newspack-custom-content-migrator.php
src/Command/PublisherSpecific/TheFifthEstateMigrator.php

This PR contains the migration for the Publisher "The Fifth Estate".
There is a command available to clean up all Orders from 22 Dec 2022. The command can be used like this:
```
wp newspack-content-migrator tfe-cleanup-orders-from-22dec2022
```
There is also a `dry-run` flag that won't proceed with the deletion.
```
wp newspack-content-migrator tfe-cleanup-orders-from-22dec2022 --dry-run
```
ℹ️ All of the logging is saved in a file with the name `tfe-cleanup-orders-from-22-dec-2022.log`
---

TFE Migrator

---

src/Command/General/InlineFeaturedImageMigrator.php

This PR adds support for Gutenberg Blocks when checking if the Featured Image is used **anywhere** in post content.
The command for this is:
```
newspack-content-migrator hide-featured-image-if-used-in-post-content --anywhere-in-post-content
```
Currently, when the `--anywhere-in-post-content` flag is used, the command searches for a full match between the Featured Image src and the post content. However, when using Gutenberg Image Block, the image src in the post content can be a resized one which led to a mismatch and thus the command wasn't fully working.

Add support for blocks in inline featured image migrator

---

src/Command/PublisherSpecific/LAFocusMigrator.php

This PR adds a set of commands to hide Featured Images on Single Post screen if used in Post Content.
The set of commands:
```
// Hide Featured Images used in Post Content
// Alias of `newspack-content-migrator hide-featured-image-if-used-in-post-content --anywhere-in-post-content`
newspack-content-migrator lafocus-hide-featured-image-if-used-in-post-content
// Hide Featured Images used in Post Content when used as External Image
newspack-content-migrator lafocus-hide-featured-images-on-posts-with-external-image-in-post-content
```
The reason behind having two commands is that:
* The first command works for images that are used internally in the Post Content either plain or as Gutenberg Block (support added https://github.com/Automattic/newspack-custom-content-migrator/pull/466)
* The …

LAFocus: Add commands to hide Featured Images when used in post content

---

src/Command/General/ContentDiffMigrator.php

- when running content diff, the defaults will now migrate only `post,attachment` types, no longer pages
---

Cdiff defaults are to migrate only attachment and post (no longer page)

---

src/Command/General/InlineFeaturedImageMigrator.php
src/Command/General/PostsMigrator.php

This general use CLI will add postmeta `newspack_featured_image_position = 'hidden'` to all posts that have a featured image.
Usage: `wp newspack-content-migrator hide-all-featured-images`
Output log: `hide_all_featured_images.log`
Note:
- There is a similar existing command (`newspack-content-migrator hide-featured-images`) in file (`src/Command/General/PostsMigrator.php`).  After reviewing that command it would have been more work to refactor it for this new use case.  The existing command requires a list of post ids and/or a category id.  Our use case doesn't call for a list of post ids nor category id.  Additionally the existing command needs to be called multiple times in order to process all rows (or use a very high `posts-per-batch` count that could take up too much processing …

Add / Hide All Featured Images

---

src/Command/General/SimplyGuestAuthorNameMigrator.php

Fixed previous [PR](https://github.com/Automattic/newspack-custom-content-migrator/pull/459) so that the loop will cycle through all posts that contain the postmeta value.  The previous PR had a `tax_query` that did not work well with the `throttled_posts_loop` function.  There is no change to the usage.  This new code just fixes a bug that hadn't been seen yet.  
---

Fix / Simply Guest Author Name Plugin loop

---

src/Command/General/VillageMediaCMSMigrator.php
src/Logic/CoAuthorPlus.php

- `src/Logic/CoAuthorPlus.php` now got the [`validate_authors_for_post()` method](https://github.com/Automattic/newspack-custom-content-migrator/pull/449/files#diff-3b3907a8903c8530c7ae54522ed347ac5029ef6eb105bfcc0cc36ff68542261fR367)
- CAP's built-in functionality to assign GAs to Post does not have a return parameter. This makes validation difficult
- now executing this validation as a part of every call to these two methods we have for assigning GAs to post, and they will throw an exception if author assignment was not successful. Suggesting to @Automattic/newspack-launch-and-infrastructure that we always use these two methods when assigning GAs, because they now contain validation:
- `assign_authors_to_post` -- assigns any user objects as guest author (either WP_Users or GA objects)
- …

Village Media CMS -- fix post authors

---

newspack-custom-content-migrator.php
src/Command/General/TagDivThemesPluginsMigrator.php

This PR sets up a general command file for CLIs related to migrating [TagDiv](https://tagdiv.com/) Themes and Plugins.  This initial command will migrate authors to CAP GAs.
Command: `newspack-content-migrator migrate-tagdiv-authors-to-gas`
Output Log: `TagDivThemesPluginsMigrator_cmd_migrate_tagdiv_authors_to_gas.log`
Required: CoAuthorPlus [plugin](https://wordpress.org/plugins/co-authors-plus/) installed and activated.
Optional Flags:
`--overwrite-post-gas` will overwrite existing GAs on posts (default: do not process posts where GAs are already set).
Notes:
- Multiple author strings will not be broken up.  Only one GA will be created per postmeta string.
---

Add / TagDiv Themes and Plugins Migrator

---

src/Command/General/EmbarcaderoMigrator.php
src/Command/General/InlineFeaturedImageMigrator.php

- there is no need for the logic which separately works on blocks. The existing fetching of `<img src>` works well both on blocks and HTML
- removed this whole block, because the `$this->attachments->import_external_file` has a more advanced inner function where it will fetch existing attachment if it already exist -- [check this](https://github.com/Automattic/newspack-custom-content-migrator/blob/trunk/src/Logic/Attachments.php#L112). Also aways use `$this->attachments->import_external_file` when importing images in migration scripts since that's our team's standard
```
// Import attachment if it doesn't exist.
$att_id = 
$attachment = get_post( $att_id );
if ( $attachment ) {
...
```
- Updated comment to clarify what code was doing
```
fom: // The code below strips the CDN _pattern_ to …
```

Fix cmd_set_first_image_from_content_as_featured_image

---

src/Command/General/EmbarcaderoMigrator.php

Command `cmd_fix_post_times` only addressed stories CSVs.
Here added a new command `cmd_fix_post_times_for_blogs_topics` which fixes dates for blog/topic CSVs.

Fix imported blog topics dates

---

src/Command/PublisherSpecific/CCMMigrator.php

This PR adds two commands to migrate brands to a temporary post meta and then migrate them back as brands.

feat(CCMMigrator): brands migration commands

---

src/Command/General/AttachmentsMigrator.php

This is a generic fixer that fixes image blocks that are not pointing to an attachment ID. Those blocks become really hard to work with the for publisher, because it's not pointing to the media library. This finds those blocks and fixes them.
The `wp newspack-content-migrator attachments-repair-img-blocks-w-no-id` command is added. It currently only takes "num items" as an arg, but we can add to that when we need it.
You need a broken block. Something like this:
```html
<figure class="wp-block-image is-resized"><img src="https://some-site.local/wp-content/uploads/2021/08/1Scv2cG3bvsYJC5ZBVRQcKA.jpeg?ssl=1" alt="" height="295" width="400"/><figcaption class="wp-element-caption">Some capation</figcaption></figure>
```
The image should be in the media library already. If it's not the code …

Add a fixer for image blocks that are "unattached" to the image

---

src/Logic/ContentDiffMigrator.php

This fixes an edge case bug where the collations array was not "compacted" with array values.
---

Avoid returning an array with null entries

---

src/Command/General/MediumMigrator.php

Medium uses `data-width` and `data-height` attributes for images in articles. These dimensions don't make sense in the context of uploading the images in WordPress. The Medium Migrator command was importing the images into the Media Library but was leaving the incorrect dimensions in the post content.
In addition, the caption related to the image was not updated on the uploaded Attachment.
To fix both issues the Migrator has been updated to:
* parse the related image caption and use it as a caption for the Attachment
* replace the whole image with a Gutenberg Image Block
You will need a Medium Export Archive to run the migration locally. Ping me and I can send a sample to you 😊
---

Medium Migrator: Change Inline Images Handler

---

src/Logic/Attachments.php

Although `$attachment_id` is an integer value, it technically remains a string because that's how it's returned from the `$wpdb` query result. To match the DocBlock description of the return values, a call to `intval` has been added to ensure that the `$attachment_id` being return is indeed an integer.
---

fix: type casting `$attachment_id` to `int`. Now matches DocBlock.

---

src/Logic/ContentDiffMigrator.php

I ran this on a staging site and confirmed that the missing authors were properly created after a recent jetpack content refresh found them to be missing.
---

Func was returning ID for recently inserted `wp_usermeta` row, not `wp_users` ID as intended.

---

newspack-custom-content-migrator.php
src/Command/PublisherSpecific/ArkansasTimesMigrator.php

This PR adds a migration command for Arkansas Times.
1. The following command can be used to migrate CPT Issues to regular Posts associated with "Issues" Category.
```
wp newspack-content-migrator arkansastimes-migrate-issues-from-cpt-to-posts
```
2. The following command can be used to migrate Media Credits from ACF to Newspack Plugin.
```
wp newspack-content-migrator arkansastimes-migrate-attachments-media-credits
```
---

Arkansas Times Migration

---

src/Command/General/InlineFeaturedImageMigrator.php

This PR is a continuation of https://github.com/Automattic/newspack-custom-content-migrator/pull/475.
It adds the removed support for image blocks parsing.
The logic is to loop through each image block of a Post and test if it can be used as a Featured Image. If such blocks don't exist or the images inside are not an actual Attachment, continue with the raw post content parsing.
---

Add support for image blocks

---

src/Logic/CoAuthorPlusDataFixer.php

These functions are primarily for convenience. They help one extract, in a consistent manner, some important pieces of data that are embedded in the `description` column for `author` term records that are generated by the CAP plugin. 
---

feat: adding two new functions that extract an ID and Email from CAP generated `author` terms.

---

composer.json
src/Command/PublisherSpecific/CarsonNowMigrator.php

This makes the Drupal migrator a bit more re-usable for other sites by using more env vars and making the database connection use env vars too so we can run on staging without having to touch passwords.
I also added convenience commands to composer.json for phpcs and phpcbf.
- It's run already

Add tweaks for drupal migration

---

composer.json
composer.lock

I was using `dev-trunk` to get the latest from the NMT. That got confusing really quick, so this starts us using releases instead. 
- composer install and check that you can run some wp cli commands with no error.
---

Use an actual release of NMT in composer to avoid confusion

---

src/Logic/GutenbergBlockGenerator.php

Gutenberg helper class's `get_image` which returns an Image block, now gets the ability to not only use `$link_to_attachment_url` but also a `$custom_link`. The image block can normally use both these links.

Image block with custom link (from old PR#324)

---

pull_request_template.md
src/Command/General/ContentDiffMigrator.php
src/Logic/ContentDiffMigrator.php

Before this PR only those WP_Users which are authors to posts were migrated. This change migrates all the WP_Users so that WooComm subscribers have their user objects automatically migrated as well.
This PR was branched off of #516 `feat/import-custom-taxonomies-with-cdiff`. Therefore when merging, make sure to merge #516 first, then if there were any new changes on `feat/import-custom-taxonomies-with-cdiff` merge them into this branch, and only then merge this branch.
- create two test sites, one to emulate the Live site, another to emulate the Staging site
- run a Content Diff scenario,
- put some content on Live site
- make Staging site as a clone of the Live site
- next, put some new content on the Live site:
- create several WP_Users, some authors to posts, others not authors to …

CDiff migrates all WP_Users

---

.github/workflows/phpcs.yml
composer.json
composer.lock
newspack-custom-content-migrator.php

This GH action will run phpcs on the code touched in PRs. 
It has to do some juggling of json in the composer file to (lazily) avoid the private repositories in there, but since we only need the stuff in `require-dev` for running phpcs we should be fine.
The easiest way to test is to push a change with some borked formatting in a PHP file and see the result, so there is a file that has that in here. I'll remove that before merging.

Add phpcs check on code in PRs

---

phpcs.xml
src/Command/PublisherSpecific/CarsonNowMigrator.php
src/Utils/ConsoleColor.php

We had a few lines that would fatal in PHP 8.3. This fixes that. It also changes the version phpcs checks against.
- Run:
-  `composer run-script phpcs -- -p --standard=PHPCompatibility --runtime-set testVersion 8.1 src`
-  `composer run-script phpcs -- -p --standard=PHPCompatibility --runtime-set testVersion 8.1 tests`
-  `composer run-script phpcs -- -p --standard=PHPCompatibility --runtime-set testVersion 8.3 src`
-  `composer run-script phpcs -- -p --standard=PHPCompatibility --runtime-set testVersion 8.3 tests`
- They should all come back with no errors.

Make code php 8.3 compliant

---

src/Command/General/AttachmentsMigrator.php

Some non static Attachment logic class methods were called as if they were static, which threw fatals.

Fix calling non-static Attachment logic class methods

---

newspack-custom-content-migrator.php
src/Logic/ContentDiffMigrator.php

`wp_comments.user_id` is expected to be found in `wp_users` table. This is not the case with one of our publishers DB -- apparently one of the two custom plugins they were using to manage comments and spam left some unreferenced and invalid user IDs in their live DB. This PR handles such an exception cases.
Also did a very small PHPCS cleanup, and improved one existing warning message.
CDiff regular run on this particular publisher.
---

Handle exception when comment user data is missing from DB

---

src/Command/General/VillageMediaCMSMigrator.php

We discovered that various authors were created without emails. This presents a problem as email is a very required field for WP. This small fix ensures that we always have an email for data migrated from Village Media.
1. Use a previous export from a Village Media CMS.
2. Pick an author, and ensure that you remove any references to their email.
3. Run the import migration on that export file.
4. Observe that although you removed their email, the user now has an email populated.
5. Now remove both email and username fields from export.
6. Re-import the data.
7. Notice that the migration is now throwing a warning showing that the email field for that user is blank.

fix: this fix ensures that `user_email` will always have a value.

---

composer.lock
src/Utils/CommonDataFileIterator/CSVFile.php

There are some CSV files that have an extra line item at the end of it. It's empty though. But this means that `feof` returns `false` though. This then then leads to trying to get this row with `get_row` and the `fgetcsv` call returning `false` instead of an expected array.
These changes will now let `get_row` to return `bool` (which can happen when calling `fgetcsv`), and when a `bool` is received, it means we have reached the end of file, there are no more rows to process, so we should either return/exit out of the current function or throw an Exception.
1. Open the attached CSV:
> $csv = new \NewspackCustomContentMigrator\Utils\CommonDataFileIterator\CSVFile( $path_to_file );
2. Get an iterator:
> $it = $csv->getIterator();
3. Loop through, see that an PHP fatal is thrown before …

fix: issue where EOF is reached prematurely, and `get_row` returns bool
